# Generated by Django 3.0.8 on 2020-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qwheel_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('A', 'Admin'), ('V', 'Vendor'), ('U', 'User')], default='U', max_length=10),
        ),
    ]
