# Generated by Django 3.0.8 on 2020-08-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qwheel_App', '0002_auto_20200808_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_img',
        ),
    ]
